import = [
    "~/.config/alacritty/themes/themes/zenburn.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
]
# more on https://github.com/alacritty/alacritty-theme

[window]
dimensions = { columns = 90, lines = 48 }
dynamic_padding = true

decorations = "Transparent"
padding = { x = 8, y = 30 }
opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 14.5
offset = { x = 0, y = 1 }

[bell]
duration = 2

[selection]
save_to_clipboard = true
