;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        beginning-of-visual-line
        describe-key
        electric-newline-and-maybe-indent
        end-of-visual-line
        evil-emacs-state
        evil-force-normal-state
        evil-forward-char
        evil-normal-state
        evil-scroll-page-down
        evil-yank
        kill-region
        kill-visual-line
        mouse-minor-mode-menu
        org-delete-char
        org-end-of-line
        org-self-insert-command
        rectangle-number-lines
        skeleton-pair-insert-maybe
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        evil-backward-char
        evil-delete-backward-char-and-join
        reindent-then-newline-and-indent
        ))
