#!/bin/bash
# To clean the temporary files generated by org-mode when exporting to LaTeX

for filename in `ls *.org`
do
    fn="${filename%.*}"
#    echo $fn
    rm ${fn}.aux ${fn}.log ${fn}.blg ${fn}.bbl ${fn}.pyg
    rm -i ${fn}.tex ${fn}.pdf
done

