#+TITLE:    The Family Box of Packages by abo-abo
#+AUTHOR:   Zuogong Yue
#+EMAIL:    oracleyue@gmail.com
#+DATE:     01 May 2018
#+STARTUP:  indent
#+OPTIONS:  H:6 num:t toc:t ^:nil _:nil \n:nil LaTeX:t


*  Ivy - a generic completion frontend (swiper, counsel, etc.)

** Requirements
*** Install system commandline tools

Tools to be installed in order to use the corresponding commands in Ivy:
(package names in Homebrew)

- ~counsel-ag~  : ~ag~ from =the_silver_searcher=
- ~counsel-ack~ : ~ack~ from =ack=
- ~counsel-rg~  : ~rg~ from =ripgrep=
- ~counsel-git~ : ~git~
- ~counsel-fzf~ : ~fzf~ (a command-line fuzzy finder)

*** Install packages for Emacs

  #+BEGIN_SRC emacs-lisp
    ;; ===============================================================
    ;; Ivy - a generic completion mechanism for Emacs
    ;; ===============================================================
    ;; Last modified on 31 Mar 2018


    ;; Install required Emacs packages
    (setq custom/ivy-ext-packages
          '(ivy
            counsel
            swiper
            counsel-projectile
            counsel-gtags))
    (custom/install-packages custom/ivy-ext-packages)
  #+END_SRC

** Ivy, Counsel and Swiper

List of frequent commands:

- grep buffer: ~swiper~ or ~counsel-grep-or-swiper~ (large files) (=C-s=)
- grep directory (recursively):
  - ~counsel-ag~
  - ~counsel-ack~
  - ~counsel-rg~ (=M-g s=) (for large files)
- grep git projects:
  - ~counsel-git~ (=C-c g=) (select a file tracked by git)
  - ~counsel-git-grep~ or use ~counsel-rg~ instead
- find files in directory recursively ~counsel-fzf~ (=M-g f=)

*** Basics
#+BEGIN_SRC emacs-lisp
  ;; ---------------------------------------------
  ;; /Ivy + Counsel + Swiper/: by abo-abo
  ;; ---------------------------------------------

  ;; Configurations
  (ivy-mode 1)
  (setq ivy-height 15)
  (setq ivy-use-virtual-buffers t)
  (setq enable-recursive-minibuffers t)
  (setq ivy-use-selectable-prompt t)  ;; make inputs selectable
#+END_SRC

*** Keybindings

Ivy-based interface to standard commands:
#+BEGIN_SRC emacs-lisp
  ;; (global-set-key (kbd "C-s") 'swiper)  ;; replace by counsel-grep-or-swiper
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "<f1> l") 'counsel-find-library)
  (global-set-key (kbd "<f2> k") 'counsel-descbinds)
  (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
  (global-set-key (kbd "C-c C-r") 'ivy-resume)
#+END_SRC


Ivy-based interface to basic editing and programming
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-y") 'counsel-yank-pop)
  (global-set-key (kbd "M-g SPC") 'counsel-mark-ring)  ;; M-SPC
  (global-set-key (kbd "M-g i") 'counsel-semantic-or-imenu) ;; C-c i
#+END_SRC

Ivy-based interface to shell and system tools:
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c g") 'counsel-git)
  ;; (global-set-key (kbd "C-c j") 'counsel-git-grep)  ;; replaced by counsel-rg
  ;; alternative ~swiper~ for large files
  (global-set-key (kbd "C-s") 'counsel-grep-or-swiper)
  (setq counsel-grep-base-command
   "rg -i -M 120 --no-heading --line-number --color never '%s' %s")
  ;; (global-set-key (kbd "M-g a") 'counsel-ag)    ;; C-c k
  ;; (global-set-key (kbd "M-g a") 'counsel-ack)
  (global-set-key (kbd "M-g a") 'counsel-rg)    ;; large files
  (global-set-key (kbd "M-g f") 'counsel-fzf)   ;; helm-find
  ;; (global-set-key (kbd "M-g l") 'counsel-locate)  ;; C-x l
#+END_SRC

*** Minibuffer actions

One may go to the INFO page (=C-h i=) of Ivy to see the complete manual.

The recommended setting of additional minibuffer actions:
#+BEGIN_SRC emacs-lisp
  (define-key minibuffer-local-map (kbd "C-r")
    'counsel-minibuffer-history)
  ;; ensure recentf-list loaded on startup
  (with-eval-after-load 'counsel (recentf-mode))
#+END_SRC

More customization of minibuffer actions to mimic =helm=:
#+BEGIN_SRC emacs-lisp
  ;; helm-like actions
  (require 'ivy)
  (require 'counsel)
  ;; (define-key ivy-switch-buffer-map (kbd "C-o")
  ;;   'counsel-recentf)  ;; use "C-r" set before
  (define-key counsel-find-file-map (kbd "C-l")
    'counsel-up-directory)
#+END_SRC

A brief summary of useful minibuffer actions:
-  =C-M-j=: exits with the current input instead of candidates;
-  =M-i=: insert the current candidate into the minibuffer;
-  =M-o=: presents valid actions;
-  =C-j=: start a new completion; otherwise, same as =RET=;
-  =TAB=: attempts partial completion; =TAB TAB= same as =C-j=;
-  =M-n=, =M-p=: cycles through the Ivy command history;
-  =S-SPC=: deletes the current input and rests the list.

*** Advanced features of ripgrep and counsel-rg

(source: https://oremacs.com/2018/03/05/grep-exclude/)

The main two commands in ivy that I use for Git are:
-  ~counsel-git~: select a file tracked by Git
-  ~counsel-rg~: grep for a line in all files tracked by Git, using =ripgrep= as
  the backend.

Among the available grep tools, ~counsel-rg~ is the fastest, especially when we
have to deal with Git repositories that more than 1GB in size. Moreover, adding
an =.ignore= file to the root of your project can really speed up your
searches. In my sample project, I went from 10k files to less than 500 files.

Example of =.ignore= files:
#+BEGIN_EXAMPLE
  /TAGS
  ,*.min.js*
  /Build/Output/
  /ThirdParty/
#+END_EXAMPLE

As you can see, both file patterns and directories are supported. One other
nifty thing that I discovered only recently is that you can use =ripgrep= as the
backed for ~counsel-git~ in addition to ~counsel-rg~. Which means the same
=.ignore= file is used for both commands. Here's the setting:

#+BEGIN_SRC emacs-lisp
  (setq counsel-git-cmd "rg --files")
#+END_SRC

And here's the setting for ~counsel-rg~:

#+BEGIN_SRC emacs-lisp
  (setq counsel-rg-base-command
        "rg -i -M 120 --no-heading --line-number --color never %s .")
#+END_SRC

The main difference in comparison to the default =counsel-rg-base-command= is
=-M 120= which means: truncate all lines that are longer than 120
characters. This is really helpful when Emacs is accepting input from =ripgrep=: a
megabyte long line of minified JS is not only useless since you can't see it
whole, but it will also likely hang Emacs for a while.

** Ivy for projectile

#+BEGIN_SRC emacs-lisp
  ;; ---------------------------------------------
  ;; /counsel-projectile/: Ivy for projectile
  ;; ---------------------------------------------
  (counsel-projectile-mode)
#+END_SRC

One may go to =~/.emacs.d/init/readme/= to see more the complete manual (the
README.md from the author's github project)

The most frequent used operations:
-  =C-c p p=: switch project
-  =C-c p f=: jump to a project file
-  =C-c p d=: jump to a project directory
-  =C-c p b=: jump to a project buffer
-  =C-c p s g=: search project with grep
-  =C-c p s s=: serach project with ag

-  =C-c p SPC=: jump to a project buffer, file, or switch project
-  =C-c p s r=: search project with rg
-  =C-c p O=:   Org-capture into project

** Ivy for GNU global tags

Enable =gtags= for the given major modes:
#+BEGIN_SRC emacs-lisp
  ;; ---------------------------------------------
  ;; /counsel-gtags/: Ivy for gtags (GNU global)
  ;; ---------------------------------------------
  (add-hook 'c-mode-hook 'counsel-gtags-mode)
  (add-hook 'c++-mode-hook 'counsel-gtags-mode)
  (add-hook 'python-mode-hook 'counsel-gtags-mode)
#+END_SRC

Keybindings:
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'counsel-gtags
    ;; basic jumps
    (define-key counsel-gtags-mode-map (kbd "M-.") 'counsel-gtags-dwim)
    (define-key counsel-gtags-mode-map (kbd "M-,") 'counsel-gtags-go-backward)
    (define-key counsel-gtags-mode-map (kbd "M-t") 'counsel-gtags-find-definition)
    (define-key counsel-gtags-mode-map (kbd "M-r") 'counsel-gtags-find-reference)
    (define-key counsel-gtags-mode-map (kbd "M-s") 'counsel-gtags-find-symbol)
    ;; create/update tags
    (define-key counsel-gtags-mode-map (kbd "C-c g c") 'counsel-gtags-create-tags)
    (define-key counsel-gtags-mode-map (kbd "C-c g u") 'counsel-gtags-update-tags)
    ;; jump over stacks/history
    (define-key counsel-gtags-mode-map (kbd "C-c g [") 'counsel-gtags-go-backward)
    (define-key counsel-gtags-mode-map (kbd "C-c g ]") 'counsel-gtags-go-forward))
#+END_SRC



* END

#+BEGIN_SRC emacs-lisp
  (provide 'init-ivy)
  ;; ================================================
  ;; init-ivy.el ends here
#+END_SRC
